name: Deploy HTML site to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload static site to cPanel
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      # Step 2: FTP Deploy (upload all files to cPanel public_html)
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
